name: Build & Deploy to GCP VM via Docker Hub

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image to Docker Hub
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/springboot:latest

      - name: SSH into GCP VM and run container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.GCP_VM_IP }}
          username: dev.yeachan
          key: ${{ secrets.GCP_SSH_KEY }}
          script: |
            echo '${{ secrets.DOCKERHUB_PASSWORD }}' | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
            docker stop springboot-container || true
            docker rm springboot-container || true
            docker pull ${{ secrets.DOCKER_USERNAME }}/springboot-app:latest
            docker run -d \
              --name springboot-container \
              -p 8080:8080 \
              -v /home/dev.yeachan/gcpkey.json:/app/gcpkey.json \
              -e SPRING_DATASOURCE_URL="${{ secrets.SPRING_DATASOURCE_URL }}" \
              -e SPRING_DATASOURCE_USERNAME="${{ secrets.SPRING_DATASOURCE_USERNAME }}" \
              -e SPRING_DATASOURCE_PASSWORD="${{ secrets.SPRING_DATASOURCE_PASSWORD }}" \
              -e SPRING_DATASOURCE_DRIVER_CLASS_NAME="${{ secrets.SPRING_DATASOURCE_DRIVER_CLASS_NAME }}" \
              -e SPRING_JPA_HIBERNATE_DDL_AUTO="${{ secrets.SPRING_JPA_HIBERNATE_DDL_AUTO }}" \
              -e SPRING_JPA_DEFER_DATASOURCE_INITIALIZATION="${{ secrets.SPRING_JPA_DEFER_DATASOURCE_INITIALIZATION }}" \
              -e SPRING_JPA_SHOW_SQL="${{ secrets.SPRING_JPA_SHOW_SQL }}" \
              -e SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL="${{ secrets.SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL }}" \
              -e SPRING_JPA_DATABASE_PLATFORM="${{ secrets.SPRING_JPA_DATABASE_PLATFORM }}" \
              -e SPRING_WEB_RESOURCES_ADD_MAPPINGS="${{ secrets.SPRING_WEB_RESOURCES_ADD_MAPPINGS }}" \
              -e SPRING_CLOUD_GCP_STORAGE_PROJECT_ID="${{ secrets.SPRING_CLOUD_GCP_STORAGE_PROJECT_ID }}" \
              -e SPRING_CLOUD_GCP_STORAGE_CREDENTIALS_LOCATION="file:/app/gcpkey.json" \
              -e SPRING_CLOUD_GCP_STORAGE_BUCKET="${{ secrets.SPRING_CLOUD_GCP_STORAGE_BUCKET }}" \
              -e GCP_CREDENTIAL_JSON="/app/gcpkey.json" \
              ${{ secrets.DOCKERHUB_USERNAME }}/springboot-app:latest
