name: Deploy to GCP VM

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Gradle (skip tests)
        run: ./gradlew build -x test

      - name: Copy JAR to GCP VM
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.GCP_VM_IP }}
          username: dev.yeachan
          key: ${{ secrets.GCP_SSH_KEY }}
          source: "build/libs/demo-0.0.1-SNAPSHOT.jar"
          target: "/home/dev.yeachan/"

      - name: Run Spring Boot app manually on GCP VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.GCP_VM_IP }}
          username: dev.yeachan
          key: ${{ secrets.GCP_SSH_KEY }}
          script: |
            pkill -f 'java -jar' || true
            echo '${{ secrets.GCP_CREDENTIAL_JSON }}' > /home/dev.yeachan/gcp-key.json
            nohup java -jar /home/dev.yeachan/build/libs/demo-0.0.1-SNAPSHOT.jar \
                --spring.datasource.url="$SPRING_DATASOURCE_URL" \
                --spring.datasource.username="$SPRING_DATASOURCE_USERNAME" \
                --spring.datasource.password="$SPRING_DATASOURCE_PASSWORD" \
                --spring.cloud.gcp.storage.credentials.location=/home/dev.yeachan/gcp-key.json \
                --spring.cloud.gcp.storage.project-id="$SPRING_STORAGE_PROJECT_ID" \
                --spring.cloud.gcp.storage.bucket="$SPRING_STORAGE_BUCKET" \
                > /home/dev.yeachan/app.log 2>&1 < /dev/null &
            env:
              SPRING_DATASOURCE_URL: ${{ secrets.SPRING_DATASOURCE_URL }}
              SPRING_DATASOURCE_USERNAME: ${{ secrets.SPRING_DATASOURCE_USERNAME }}
              SPRING_DATASOURCE_PASSWORD: ${{ secrets.SPRING_DATASOURCE_PASSWORD }}
              SPRING_STORAGE_PROJECT_ID: ${{ secrets.SPRING_STORAGE_PROJECT_ID }}
              SPRING_STORAGE_BUCKET: ${{ secrets.SPRING_STORAGE_BUCKET }}
