name: Deploy to GCP VM

on:
  push:
    branches:
      - Feat/CICD

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Gradle
        run: ./gradlew build

      - name: Deploy .jar to GCP VM
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.GCP_VM_IP }}
          username: dev.yeachan
          key: ${{ secrets.GCP_SSH_KEY }}
          source: "build/libs/your-app.jar"
          target: "/home/${{ secrets.GCP_VM_USER }}/"

      - name: Restart App on GCP
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.GCP_VM_IP }}
          username: dev.yeachan
          key: ${{ secrets.GCP_SSH_KEY }}
          script: |
            pkill -f demo.jar || true
            nohup java -jar demo.jar > app.log 2>&1 &
