name: Build & Deploy to GCP VM via Artifact Registry

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker asia-northeast3-docker.pkg.dev

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image to Artifact Registry
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: asia-northeast3-docker.pkg.dev/liquid-braid-463809-s5/springboot/springboot:latest

      - name: SSH into GCP VM and run container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.GCP_VM_IP }}
          username: dev.yeachan
          key: ${{ secrets.GCP_SSH_KEY }}
          script: |
            gcloud auth configure-docker asia-northeast3-docker.pkg.dev
            docker stop springboot-container || true
            docker rm springboot-container || true
            docker pull asia-northeast3-docker.pkg.dev/liquid-braid-463809-s5/springboot/springboot:latest
            docker run -d --name springboot-container -p 8080:8080 \
              -v /home/dev.yeachan/gcpkey.json:/app/gcpkey.json \
              -e SPRING_DATASOURCE_URL="${{ secrets.SPRING_DATASOURCE_URL }}" \
              -e SPRING_DATASOURCE_USERNAME="${{ secrets.SPRING_DATASOURCE_USERNAME }}" \
              -e SPRING_DATASOURCE_PASSWORD="${{ secrets.SPRING_DATASOURCE_PASSWORD }}" \
              -e SPRING_DATASOURCE_DRIVER_CLASS_NAME="${{ secrets.SPRING_DATASOURCE_DRIVER_CLASS_NAME }}" \
              -e SPRING_JPA_HIBERNATE_DDL_AUTO="${{ secrets.SPRING_JPA_HIBERNATE_DDL_AUTO }}" \
              -e SPRING_JPA_DEFER_DATASOURCE_INITIALIZATION="${{ secrets.SPRING_JPA_DEFER_DATASOURCE_INITIALIZATION }}" \
              -e SPRING_JPA_SHOW_SQL="${{ secrets.SPRING_JPA_SHOW_SQL }}" \
              -e SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL="${{ secrets.SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL }}" \
              -e SPRING_JPA_DATABASE_PLATFORM="${{ secrets.SPRING_JPA_DATABASE_PLATFORM }}" \
              -e SPRING_WEB_RESOURCES_ADD_MAPPINGS="${{ secrets.SPRING_WEB_RESOURCES_ADD_MAPPINGS }}" \
              -e SPRING_CLOUD_GCP_STORAGE_PROJECT_ID="${{ secrets.SPRING_CLOUD_GCP_STORAGE_PROJECT_ID }}" \
              -e SPRING_CLOUD_GCP_STORAGE_CREDENTIALS_LOCATION="file:/app/gcpkey.json" \
              -e SPRING_CLOUD_GCP_STORAGE_BUCKET="${{ secrets.SPRING_CLOUD_GCP_STORAGE_BUCKET }}" \
              -e GCP_CREDENTIAL_JSON="/app/gcpkey.json" \
              asia-northeast3-docker.pkg.dev/liquid-braid-463809-s5/springboot/springboot:latest
