name: Build & Deploy to GCP VM via Docker Hub

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image to Docker Hub
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/springboot:latest

      - name: SSH into GCP VM and run container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.GCP_VM_IP }}
          username: dev.yeachan
          key: ${{ secrets.GCP_SSH_KEY }}
          script: |
            echo '${{ secrets.DOCKERHUB_PASSWORD }}' | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
            docker stop springboot-container || true
            docker rm springboot-container || true
            docker pull ${{ secrets.DOCKER_USERNAME }}/springboot:latest
            docker run -d \
              --name springboot-container \
              -p 8080:8080 \
              -e SPRING_PROFILES_ACTIVE=dev \
              -e SPRING_DATASOURCE_URL=${{ secrets.SPRING_DATASOURCE_URL }} \
              -e SPRING_DATASOURCE_USERNAME=${{ secrets.SPRING_DATASOURCE_USERNAME }} \
              -e SPRING_DATASOURCE_PASSWORD=${{ secrets.SPRING_DATASOURCE_PASSWORD }} \
              -e SPRING_STORAGE_PROJECT_ID=${{ secrets.SPRING_STORAGE_PROJECT_ID }} \
              -e SPRING_STORAGE_BUCKET=${{ secrets.SPRING_STORAGE_BUCKET }} \
              ${{ secrets.DOCKER_USERNAME }}/springboot:latest
